### PR TITLE
Port to Rust 0.10

### PR DESCRIPTION
**Pull request by nathantypanski**
This doesn't have a working cstring implementation, but I would argue that any Rust code written for 0.9 is going to become worthless exponentially fast now that 0.10 is out. Any future efforts should focus on improving a 0.10 version, not dragging 0.9 through the dirt.

In case anyone decides to work off this codebase later, we would do well to have a bootable 0.10 version in `master`.

### CODE REVIEW

**Comment by lenary** [comment]
once streq is fixed... :P

**Comment by nathantypanski** [comment]
Noo!

... ok.

**Comment by nathantypanski** [comment]
rusty

:)

**Comment by lenary** [comment]
woop woop :) :+1:

**Pull request merged**
